singleQuote: true
tabWidth: 2
trailingComma: all
printWidth: 80
semi: true
overrides:
  - files: "*.ts *.mts *.js *.mjs *.cjs"
    options:
      tabWidth: 2
plugins:
  - './node_modules/prettier-plugin-sort-imports/dist/index.js'
sortingMethod: 'alphabetical'
